### PR TITLE
dojo 1.7.0

### PR DESCRIPTION
**Pull request by william-gr**

### CODE REVIEW

**Comment by klipstein** [comment]
Did you test your environment with Dojo 1.7.0? With this patch Dojango fails when loading the dojo.xd.js from google. Dojo 1.7.0 completely got rid of the separation of the xd/non-xd loader conecpt and the following URL is generated by dojango:

http://ajax.googleapis.com/ajax/libs/dojo/1.7.0/dojo/dojo.xd.js

The right URL would be:

http://ajax.googleapis.com/ajax/libs/dojo/1.7.0/dojo/dojo.js

And it seems that dojango needs a bigger patch to reflect the complete new loading mechanism of dojo.

**Comment by william-gr** [comment]
On Mon, Dec 5, 2011 at 8:06 PM, klipstein
reply@reply.github.com
wrote:

> Did you test your environment with Dojo 1.7.0? With this patch Dojango fails when loading the dojo.xd.js from google. Dojo 1.7.0 completely got rid of the separation of the xd/non-xd loader conecpt and the following URL is generated by dojango:
> 
> http://ajax.googleapis.com/ajax/libs/dojo/1.7.0/dojo/dojo.xd.js
> 
> The right URL would be:
> 
> http://ajax.googleapis.com/ajax/libs/dojo/1.7.0/dojo/dojo.js

I did but likely it was a cache issue on my side...

> And it seems that dojango needs a bigger patch to reflect the complete new loading mechanism of dojo.

Not really, you can use 1.7 with the old system, you don't _have_ to use AMD.

## 

## William Grzybowski

Agência Livre - www.agencialivre.com.br
Curitiba/PR - Brasil

**Comment by klipstein** [comment]
I've fixed Dojango to use Dojo 1.7.0 here:

https://github.com/klipstein/dojango/compare/a5af5834b99ce44cc935478eeac602e02f4ce755...master

Thanks for remembering me to upgrade to Dojo 1.7.0. I'm not applying your patch because it was non-functional (as commented before: the simple version setting of 1.7.0 will generate the non-existent URL http://ajax.googleapis.com/ajax/libs/dojo/1.7.0/dojo/dojo.xd.js). Closing the issue, because Dojango is able to handle Dojo 1.7.0 now.

**Comment by william-gr** [comment]
Roger that, thank you sir.

On Wed, Dec 7, 2011 at 9:26 PM, klipstein
reply@reply.github.com
wrote:

> I've fixed Dojango to use Dojo 1.7.0 here:
> 
> https://github.com/klipstein/dojango/compare/a5af5834b99ce44cc935478eeac602e02f4ce755...master
> 
> Thanks for remembering me to upgrade to Dojo 1.7.0. I'm not applying your patch because it was non-functional (as commented before: the simple version setting of 1.7.0 will generate the non-existent URL http://ajax.googleapis.com/ajax/libs/dojo/1.7.0/dojo/dojo.xd.js). Closing the issue, because Dojango is able to handle Dojo 1.7.0 now.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/klipstein/dojango/pull/95#issuecomment-3055339

## 

## William Grzybowski

Agência Livre - www.agencialivre.com.br
Curitiba/PR - Brasil

**Pull request closed without merging**
